esphome:
  name: "ikea-fornuftig"

esp8266:
  board: d1_mini
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Luftrenser Fallback Hotspot"
    password: !secret fallback_wifi_passcode

captive_portal:

output:
  - platform: gpio
    pin: 
      number: GPIO04
      inverted: true
    id: fan_off
  - platform: gpio
    pin: 
      number: GPIO05
      inverted: true
    id: fan_low
  - platform: gpio
    pin: 
      number: GPIO12
      inverted: true
    id: fan_medium
  - platform: gpio
    pin: 
      number: GPIO13
      inverted: true
    id: fan_high

  - platform: template
    id: fan_speed
    type: float
    write_action:
      - output.turn_off: fan_off
      - output.turn_off: fan_low
      - output.turn_off: fan_medium
      - output.turn_off: fan_high
      - if:
          condition:
            - fan.is_off: luftrenser
          then:
            - logger.log: Fan off
            - output.turn_on: fan_off
      - if:
          condition:
            - fan.is_on: luftrenser
            - lambda: |-
                if (id(luftrenser).speed == 1) {
                  return true;
                } else {
                  return false;
                }
          then:
            - logger.log: Fan low
            - output.turn_on: fan_low 
      - if:
          condition:
            - fan.is_on: luftrenser
            - lambda: |-
                if (id(luftrenser).speed == 2) {
                  return true;
                } else {
                  return false;
                }
          then:
            - logger.log: Fan medium            
            - output.turn_on: fan_medium
      - if:
          condition:
            - fan.is_on: luftrenser
            - lambda: |-
                if (id(luftrenser).speed == 3) {
                  return true;
                } else {
                  return false;
                }
          then:
            - logger.log: Fan high
            - output.turn_on: fan_high

fan:
  - platform: speed
    id: luftrenser
    name: Luftrenser
    output: fan_speed
    speed_count: 3
    restore_mode: ALWAYS_OFF
